name: 'Dismiss stale reviews'
description: 'Dismisses stale reviews on a pull request if the diff has changed'
author: 'Graphite'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

inputs:
  github-token:
    description:
      'A GITHUB_TOKEN secret or PAT that has write access to the repository'
    required: true

runs:
  using: node20
  main: dist/index.js
