name: 'Dismiss stale reviews'
description: 'Dismisses stale reviews on a pull request if the diff has changed'
author: 'Graphite'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

runs:
  using: node20
  main: dist/index.js
